# IMPORTANTE:
# El url, username & password se exponen porque es una practica. 
# En una aplicacion real, estos datos son sensibles, por lo que se debe utilizar variables de entorno.
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inmobiliaria
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      data-locations: classpath:database.sql
